### ISSUE TITLE
DL: Investigate sessions incompletions after constraint violations

### ISSUE THREAD

**Issue by eignatik** [perfo-foundation/prt-datalayer#13]
## Problem.
When constraint violation appears after that it's not possible to continue operations in this session because Transcation in use or something like that.

## TODO
- [ ] check that session can be completed or switched after violation
- [ ] check how session works in that case
- [ ] figure out how to avoid
- [ ] or figure out how to redesign session utilities or generic DAO
