### ISSUE TITLE
DL: Figure out which date format will be better

### ISSUE THREAD

**Issue by eignatik** [perfo-foundation/prt-datalayer#15]
### Problem
In Sql2o data is stored in different format. In different DB it could be stored in different ways.

### TODO
- [ ] check possibility to pick up a suitable data format
- [ ] check if it's possible to keep using Date in DB, maybe it's better to store data in String
- [ ] refactor DB and code if needed

### Remark:
There is a chance that this issue will be blocked by another one "Create directory to store SQL procedures and their rollbacks for DB"
