### ISSUE TITLE
DL: Create a directory to store SQL procedures and their rollbacks for DB

### ISSUE THREAD

**Issue by eignatik** [perfo-foundation/prt-datalayer#16]
### Problem
There is a big chance that in future we will need to change something in DB (structure, data, reconciliation things, etc). It means that we need to create a simple possibility to store scripts which should be applied and their rollback scripts as well in case of issues. 

### TODO:
- [ ] create directory with scripts
- [ ] create directory with rollbacks
- [ ] update documentation about that
